### ISSUE TITLE
V0.3 feedback

### ISSUE THREAD

**Issue by jeffryhartanto** [CS2103AUG2016-W11-C3/main#115]
# Developer Guide
- Fix formatting in the `Troubleshooting Project Setup`.
- In the SD for `delete` command's EventCenter, the `delete` command should run before raising event, right?
- What is this? `To find an item, the user will search through the Storage by calling "find ", "find " or "find ".`
- Please proofread the document again, as I see some typos here and there. :)
- You can also provide the SD for undo/redo, as it might be interesting to know how you implement one of those commands. Similarly, you can explain other interesting design decisions you made.
# User Guide
- Nice GUI, though I remember your current design doesn't reflect your design here. So, you need to choose which one to change.
- No FindTag in the Developer Guide, you guys need to decide what to do.
- For `Repeat` command, consider using UP arrow to do so.
- Think how to optimize the UI further. It looks nice and polished, but is it as useful as it can be? Can it show at a whole day's schedule at a time? When you add/edit/delete, does it give visual cues to confirm what happened was exactly what user intended?
- The 'Command summary' section will be used heavily by our testers. Try to make it easy to use as possible. e.g. give examples for each command.

**Comment by jeffryhartanto** [comment]
Take a look at this [handout](https://docs.google.com/document/d/1kAth-pTOzwCJFVjS6KU8O50bCvijDqpb6GsOyJTD0Ds/pub?embedded=true) if you haven't done so. You may have similar issues..

**Comment by zavfel** [comment]
implemented the UP arrow for `Repeat`
