### ISSUE TITLE
Features: Add Function (Refinement needed)

### ISSUE THREAD

**Issue by LuMiN0uSaRc** [CS2103AUG2016-W11-C3/main#13]
To be done by end of Week 8

**Comment by LuMiN0uSaRc** [comment]
- Specify deadlines
- Specify the format of the inputs (e.g time - the start and end time?) 
- Aliases confirmation 
- tags

**Comment by LuMiN0uSaRc** [comment]
- How can we handle duplicates? -> indexes

**Comment by kfwong** [comment]
Completed as of PR #53
