### ISSUE TITLE
Boost our Test Coverage to 80+

### ISSUE THREAD

**Issue by kfwong** [CS2103AUG2016-W11-C3/main#153]

**Comment by bertojo** [comment]
test cases for XmlTaskManagerStorage done

**Comment by kfwong** [comment]
#203 Covered ImportCommand.

**Comment by kfwong** [comment]
#204 Improved AddCommand Coverage by commented out depracated constructors.

**Comment by bertojo** [comment]
#225 added test cases for relocate

**Comment by bertojo** [comment]
hit 80% +.
