### ISSUE TITLE
Labels under task names

### ISSUE THREAD

**Issue by LuMiN0uSaRc** [CS2103AUG2016-W11-C3/main#200]
The Label under task names are not updating according to real time. Perhaps just hide the seconds to make it not so obvious if we are not fixing the updating.

**Comment by LuMiN0uSaRc** [comment]
Alternatively, make it update the time whenever user changes view.

**Comment by kfwong** [comment]
I was thinking about that too. But the utility method I'm using has limitation, I haven't figure out how not to display the seconds.

Just in case you need reference, I'm using the `DateFormatUtils` from apache commons lang library to format the time:
The method that render the labels are under `MainWindow.java`

``` java
DurationFormatUtils.formatDurationWords(long time, boolean args, boolean args);
```

**Comment by bertojo** [comment]
enhancement dropped for 0.5, left for future updates
