### ISSUE TITLE
Edit bug

### ISSUE THREAD

**Issue by bertojo** [CS2103AUG2016-W11-C3/main#207]
edit 2 sd/'tomorrow'
is considered to be a valid command but does not do anything

**Comment by kfwong** [comment]
The current implementation is that it will drop any invalid options. Need to refine regex to enforce at least 1 option is defined.

**Comment by kfwong** [comment]
Consider the bug is trivial and we are near the release date, I'll put this as a footnote under user guide to inform user any irrelevant field will be dropped if the syntax is malformed. Essentially the above command will be interpret as the follow:

```
// execute edit 2 but does not change anything since the syntax is malformed.
edit 2
```
