### ISSUE TITLE
T8A3 feedback

### ISSUE THREAD

**Issue by jeffryhartanto** [CS2103AUG2016-W11-C3/main#66]
Some comments:
# User Guide
- Make sure features you mentioned in User Guide corresponds to your latest release. As I remember you haven't implemented `redo` and `undo` in your latest release.
# Developer Guide
## User Stories
- Marking task as done should have highest priority.
- Undo is not only for task, you can just say undo the last command.
- `increase my workflow` and `find my tasks easily` may need to be more explicit and clear.
## Use Cases
- Don't forget to consider invalid command for all Use Cases.
- For commands like Edit or Delete, don't forget to mention that user may need to trigger list commands first.
- UC2: step 2 and 3 can be merge into one.
- Redo is not mentioned in the User Stories.
- You can make the use case more specific. (e.g. Add deadline) as extensions can vary based on the task type
## NFR
- In case you missed it, our module handbook specifies a number of project constraints (e.g. No Relational Databases). At least hyperlink to that document.
## Product Survey
- Good job, just fix the formatting.

**Comment by bertojo** [comment]
Hello,

For the following constraint: 
Constraint-Human-Editable-File - The data should be stored locally and should be in a human editable text file. The intention of this constraint is to allow advanced users to manipulate the data by editing the data file.

AddressBook level 4 stores the data in .xml format, so does this constraint still apply?

**Comment by jeffryhartanto** [comment]
Yes, it does. Because XML is considered a human-readable format.

**Comment by bertojo** [comment]
ok thank you!

**Comment by bertojo** [comment]
Done as of v0.3
