### ISSUE TITLE
User story: Specify own natural language 

### ISSUE THREAD

**Issue by LuMiN0uSaRc** [CS2103AUG2016-W11-C3/main#88]
Description: 
User can customize the app 

Solution/Feature: 
newCommand command?

**Comment by LuMiN0uSaRc** [comment]
Not implemented at all yet - 16.10.2016

**Comment by bertojo** [comment]
unlikely to implement, meant for future developers/ updates

**Comment by bertojo** [comment]
Left for future updates after release of mastermind
